AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure for the Cloud Resume Challenge
Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket to create
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    #https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-s3-bucket.html
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        #ErrorDocument: error.html
